from urllib.request import urlopen
import time


def scrape_walkthrough(url, filename):
    page = urlopen(url)
    html = page.read().decode("windows-1252")

    file = open("../0_datasets/bw2_" + filename + ".html", "w")
    file.write(html)
    file.close()


if __name__ == "__main__":
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/aspertiacity.shtml", "aspertia_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route19.shtml", "route_19")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/floccesytown.shtml", "floccesy_town")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route20.shtml", "route_20")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/floccesyranch.shtml", "floccesy_ranch")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/virbankcity.shtml", "virbank_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/virbankcomplex.shtml", "virbank_complex")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/pokestarstudios.shtml", "pokestar_studios")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/casteliacity.shtml", "castelia_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/casteliasewers.shtml", "castelia_sewers")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route4.shtml", "route_4")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/desertresort.shtml", "desert_resort")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/reliccastle.shtml", "relic_castle")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/joinavenue.shtml", "join_avenue")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/nimbasacity.shtml", "nimbasa_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/anvilletown.shtml", "anville_town")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route16.shtml", "route_16")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/lostlornforest.shtml", "lostlorn_forest")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route5.shtml", "route_5")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/driftveildrawbridge.shtml", "driftveil_drawbridge")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/driftveilcity.shtml", "driftveil_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/pwt.shtml", "pwt")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/plasmafrigate.shtml", "plasma_frigate")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/relicpassage.shtml", "relic_passage")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route6.shtml", "route_6")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/mistraltoncave.shtml", "mistralton_cave")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/chargestonecave.shtml", "chargestone_cave")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/mistraltoncity.shtml", "mistralton_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route7.shtml", "route_7")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/celestialtower.shtml", "celestial_tower")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/lentimastown.shtml", "lentimas_town")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/strangehouse.shtml", "strange_house")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/reversalmountain.shtml", "reversal_mountain")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/undellatown.shtml", "undella_town")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/undellabay.shtml", "undella_bay")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route13.shtml", "route_13")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/lacunosatown.shtml", "lacunosa_town")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route12.shtml", "route_12")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/villagebridge.shtml", "village_bridge")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route11.shtml", "route_11")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/opelucidcity.shtml", "opelucid_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/marinetube.shtml", "marine_tube")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/humilaucity.shtml", "humilau_city")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route21.shtml", "route_21")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/seasidecave.shtml", "seaside_cave")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/giantchasm.shtml", "giant_chasm")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/route23.shtml", "route_23")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/victoryroadb2w2.shtml", "victory_road")
    time.sleep(10)
    scrape_walkthrough("https://www.serebii.net/pokearth/unova/pokemonleague.shtml", "pokemon_league")
    time.sleep(10)
